FROM node:10

ARG WORKDIR
ARG PORT
ARG DATA_FOLDER
ARG INFLUX_URL
ARG STORAGE

ENV PORT $PORT
ENV WORKDIR $WORKDIR
ENV DATA_FOLDER $DATA_FOLDER
ENV INFLUX_URL $INFLUX_URL
ENV STORAGE $STORAGE

WORKDIR /$WORKDIR

COPY package*.json ./
RUN npm install --production && \
    npm cache clean --force

COPY . ./

EXPOSE $PORT
CMD ["sh", "-c", "npm start port=${PORT} dataFolder=${DATA_FOLDER} influxUrl=${INFLUX_URL} storage=${STORAGE}"]
